# Generated by Django 4.2.9 on 2024-01-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0003_orders_orderupdate"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderUpdate",),
    ]
